[project]
name = "artefacts-tools"
version = "0.1.0"
description = "A collection of simple, single-file tools"
requires-python = ">=3.11"

[build-system]
requires = ["setuptools>=68.0"]
build-backend = "setuptools.build_meta"
